[global]
   workgroup = WORKGROUP
   server string = GoStream
   deadtime = 15
   log level = 1
   max log size = 50
   dns proxy = no
   security = user
   map to guest = bad user
   guest account = nobody
   force user = root
   force group = root

[gostream-mkv-virtual]
   path = /mnt/gostream-mkv-virtual
   browseable = yes
   read only = no
   guest ok = yes
   oplocks = no
   level2 oplocks = no
   force user = root
   force group = root
   create mask = 0755
   directory mask = 0755