[global]
   workgroup = WORKGROUP
   server string = GoStream
   deadtime = 15
   log level = 1
   max log size = 50
   dns proxy = no
   security = user
   map to guest = bad user
   guest account = nobody

[gostream-mkv-virtual]
   path = /mnt/gostream-mkv-virtual
   browseable = yes
   read only = yes
   guest ok = yes
   oplocks = no
   level2 oplocks = no